name: 'VolksApi'

on:
  push:
    branches:
      - homologacao
  pull_request:
    branches:
      - homologacao

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Set Dotnet"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    
    - name: "Restore dependencies"  
      run: dotnet restore Parati.Dashboard.WebApi2/Parati.Dashboard.WebApi2/Parati.Dashboard.WebApi2.csproj

    - name: "Build api"  
      run: dotnet build --configuration Release Parati.Dashboard.WebApi2/Parati.Dashboard.WebApi2/Parati.Dashboard.WebApi2.csproj
      
  test:
    name: "Unit Test"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set Dotnet"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: "Restore Test dependencies"
        run: dotnet restore Parati.Dashboard.WebApi2/Parati.Dashboard.Test/Parati.Dashboard.Test.csproj

      - name: "Run tests"
        run: dotnet test --no-restore --verbosity normal Parati.Dashboard.WebApi2/Parati.Dashboard.Test/Parati.Dashboard.Test.csproj --configuration Release

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
           service-id: ${{ secrets.RENDER_SERVICE_ID }}
           api-key: ${{ secrets.RENDER_API_KEY }}
